pages:
  stage: deploy
  image: python:latest
  script:
    - chmod +x run_scripts.sh
    - ./run_scripts.sh
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == master'