pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r redirect/gitlab/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "feat/mixandcall-rearch"
